#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#Layer LED config -------------------
# Disable layer-change LED widget by default for boards without an RGB LED alias
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=n

#ZMK studio -------------------
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n 
